### ISSUE TITLE
Sharing iP code quality feedback [for @UnwilledTangent]

### ISSUE THREAD

**Issue by soc-se-script** [UnwilledTangent/ip#1]
@UnwilledTangent We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/duke/src/Duke.java` lines `8-8`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/main/duke/src/Duke.java#L8..L8):

```java

//    Scanner scanner = new Scanner(System.in);

```

Example from [`src/main/duke/src/Storage.java` lines `25-25`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/main/duke/src/Storage.java#L25..L25):

```java

                // System.out.println("File created: " + newFile.getName());

```

Example from [`src/main/duke/src/Storage.java` lines `27-27`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/main/duke/src/Storage.java#L27..L27):

```java

                // System.out.println("duke.txt already exists.");

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

Example from [`src/main/java/duke/duke/Duke.java` lines `19-134`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/main/java/duke/duke/Duke.java#L19..L134):

```java

    public static void main(String[] args) throws DukeException {
        Scanner scanner = new Scanner(System.in);

        String logo = " ____        _        \n"
                + "|  _ \\ _   _| | _____ \n"
                + "| | | | | | | |/ / _ \\\n"
                + "| |_| | |_| |   <  __/\n"
                + "|____/ \\__,_|_|\\_\\___|\n";
        System.out.println("Hello from\n" + logo);
        System.out.println(" What can I do for you?");

        String input = "";
        ArrayList<Task> tasksList = new ArrayList<Task>();

        while (!input.equals("bye")) {
            try {
                input = scanner.nextLine();
                String command = input.split(" ")[0];

                if (command.equals("bye")) {
                    System.out.println("Bye. Hope to see you again soon!");
                    saveTodoList(tasksList);
                    break;
                } else if (command.equals("list")) {
                    int taskNumber = 1;
                    System.out.println("Here are the tasks in your list:");
                    for (Task t : tasksList) {
                        System.out.println(Integer.toString(taskNumber) + ". " + t);
                        taskNumber++;
                    }
                } else if (command.equals("mark")) {
                    int taskNumber = Integer.parseInt(input.split(" ")[1]) - 1;
                    tasksList.get(taskNumber).markAsDone();
                    saveTodoList(tasksList);
                } else if (command.equals("unmark")) {
                    int taskNumber = Integer.parseInt(input.split(" ")[1]) - 1;
                    tasksList.get(taskNumber).markAsNotDone();
                    saveTodoList(tasksList);
                } else if (command.equals("todo")) {
                    try {
                        String inputWithoutCommand = input.substring(5);

                        ToDo toDo = new ToDo(inputWithoutCommand);
                        tasksList.add(toDo);

                        System.out.println("Got it. I've added this task:");
                        System.out.println(toDo);
                        System.out.println("Now you have " + tasksList.size() + " tasks in the list.");
                        saveTodoList(tasksList);
                    } catch (StringIndexOutOfBoundsException e) {
                        e.printStackTrace();
                        System.out.println("☹ OOPS!!! The description of a todo cannot be empty.");
                    }
                } else if (command.equals("deadline")) {
                    int indexOfByString = input.indexOf("/by ");
                    int indexOfDate = indexOfByString + 4;

                    String inputWithoutCommand = input.substring(9, indexOfByString - 1);

                    String date = input.substring(indexOfDate, input.length() - 1);

                    Deadline deadline = new Deadline(input.substring(9, indexOfByString), input.substring(indexOfDate));
                    tasksList.add(deadline);

                    System.out.println("Got it. I've added this task:");
                    System.out.println(deadline);
                    System.out.println("Now you have " + tasksList.size() + " tasks in the list.");
                    saveTodoList(tasksList);
                } else if (command.equals("event")) {
                    String inputWithoutCommand = input.substring(6);

                    int indexOfFromSubstring = inputWithoutCommand.indexOf("/from ");
                    int indexOfToSubstring = inputWithoutCommand.indexOf("/to ");

                    String description = inputWithoutCommand.substring(0, indexOfFromSubstring);
                    String startTime = inputWithoutCommand.substring(indexOfFromSubstring + 6, indexOfToSubstring - 1);
                    String endTime = inputWithoutCommand.substring(indexOfToSubstring + 4);

                    Event event = new Event(description, startTime, endTime);
                    tasksList.add(event);

                    System.out.println("Got it. I've added this task:");
                    System.out.println(event);
                    System.out.println("Now you have " + tasksList.size() + " tasks in the list.");
                    saveTodoList(tasksList);
                } else if (command.equals("delete")) {
                    int indexToBeRemoved = Integer.parseInt(input.split(" ")[1]);

                    Task removedTask = tasksList.remove(indexToBeRemoved - 1);

                    System.out.println("Noted. I've removed this task:");
                    System.out.println(removedTask);
                    System.out.println("Now you have " + tasksList.size() + " tasks in the list.");
                    saveTodoList(tasksList);
                } else if (command.equals("find")) {
                    String findString = input.substring(5);

                    int taskNumber = 1;

                    System.out.println("Here are the matching tasks in your list:");

                    for (Task t : tasksList) {
                        if (t.toString().contains(findString)) {
                            System.out.println(Integer.toString(taskNumber) + ". " + t);
                            taskNumber++;
                        }
                    }
                } else {
                    throw new DukeException("☹ OOPS!!! I'm sorry, but I don't know what that means :-(");
                }
            } catch (DukeException e) {
                // if you try and catch the exception, you can still continue to run the program! WOW!
                e.printStackTrace();
            }
        }
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2223s2.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/duke/Duke.java` lines `14-18`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/main/java/duke/duke/Duke.java#L14..L18):

```java

    /**
     * main class for Duke todolist
     * @param args
     * @throws DukeException
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

* [`src\test\java\production\duke\Deadline.class`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/test/java/production/duke/Deadline.class) 
            

* [`src\test\java\production\duke\Duke.class`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/test/java/production/duke/Duke.class) 
            

* [`src\test\java\production\duke\DukeException.class`](https://github.com/UnwilledTangent/ip/blob/ef9c8290c3dfdc908e2324a70e69fb60adaeb4a0/src/test/java/production/duke/DukeException.class) 
             

**Suggestion:** Avoid committing binary files (e.g., `*.class`, `*.jar`, `*.exe`) or third-party library files in to the repo.

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by UnwilledTangent** [comment]
Committed and edited code based on the above advice!
